name: 'GitHub Actions Weather Bot'

on: [push]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'echo mail username 1'
        run: echo "${{ secrets.MAIL_USERNAME }}"
      - name: 'echo mail username 2'
        run: echo ${{ secrets.MAIL_USERNAME }}
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: reuc@foxmail.com
          from: GitHub Actions
          content_type: text/html